networks:
  app_network:
    name: panchyet_network

services:
  app:
    image: ${fullTag}
    restart: always

    container_name: panchyet_app
    networks:
      - panchyet_network
    volumes:
      - "/panchyet/.env:/var/www/html/.env"
      - /SCM/ssl/:/key
    ports:
      - "9443:9443"