pipeline {
    agent any
   
    environment {
        GIT_REPO_URL = 'https://github.com/Bhargab25/Panchayet.git'
        GIT_BRANCH = 'main'
        DOCKER_IMAGE = 'panchyet'
    }

    stages {
        stage('Clone Repo') {
            steps {
                    git branch: "${env.GIT_BRANCH}", url: "${env.GIT_REPO_URL}"

            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    def commitId = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def fullTag = "${DOCKER_IMAGE}:${commitId}"

                    withCredentials([usernamePassword(
                        credentialsId: 'panchyet', 
                        usernameVariable: 'DOCKER_USER', 
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                            echo "$DOCKER_PASS" | docker login repo.kustav.co.in -u "$DOCKER_USER" --password-stdin
                            # Run composer setup inside app/app

                            docker build -t ${fullTag} .
                            docker push ${fullTag}
                            # Cleanup local image
                            docker rmi ${fullTag} || true
                            docker logout
                        """
                    }
                }
            }
        }

        stage('Start Application with Docker Compose') {
            steps {
            script {
                def commitId = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                def fullTag = "${DOCKER_IMAGE}:${commitId}"
                sh """
                export fullTag=${fullTag}  
                docker compose up -p panchyet -d  
                """
            }
            }
        }
    }
}
