pipeline {
    agent any
    triggers {
        githubPush()
    }

    environment {
        GIT_REPO_URL = 'https://github.com/Bhargab25/Panchayet.git'
        GIT_BRANCH = 'main'
    }

    stages {
        stage('Clone Repo') {
            steps {
                // Clone into Jenkins workspace
                git branch: "${env.GIT_BRANCH}", url: "${env.GIT_REPO_URL}"
            }
        }

        stage('Copy to /KCA_WEB') {
            steps {
            sh '''
                # Stop and remove existing docker-compose stack if it exists
                if [ -f /DEMO_WEB/devops/docker-compose.yml ]; then
                docker compose -p panchayet -f /KCA_WEB/devops/docker-compose.yml down || true
                fi

                # Copy new files with force overwrite
                rm -rf  /DEMO_WEB/*
                cp -rf app /DEMO_WEB/
            '''
            }
        }

        stage('Deploy') {
            steps {
                dir('devops') {
                    sh 'docker compose -p panchayet up -d'
                }
            }
        }
    }
}